services:
- type: web
  name: crosswears-backend-
  runtime: docker
  plan: free
  region: frankfurt # Sau regiunea cea mai apropiată de tine
  envVars:
    - key: SPRING_DATASOURCE_URL
      value: jdbc:mysql://shinkansen.proxy.rlwy.net:28086/railway
    - key: SPRING_DATASOURCE_USERNAME
      value: root
    - key: SPRING_DATASOURCE_PASSWORD
      value: kZKlXjITRQaQFAFdqXbewEfZoZgjEwAq # Pune parola ta reală de pe Railway
    - key: SPRING_JPA_HIBERNATE_DDL_AUTO
      value: update